name = "BackwardsLinalg"
uuid = "442b4e1a-8b9d-11e9-03b0-f14b31742153"
authors = ["JinGuo Liu", "Lei Wang"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = ">=1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
